# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestlogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testlogin(self):
    self.driver.get("https://saesdesa.ospesalud.com.ar/saes/")
    self.driver.set_window_size(1936, 1048)
    self.driver.find_element(By.LINK_TEXT, "[inicio]").click()
    self.driver.switch_to.default_content()
    self.driver.find_element(By.ID, "txtUser").send_keys("marcano01")
    self.driver.find_element(By.ID, "txtPassword").send_keys("Externo$$111")
    self.driver.find_element(By.ID, "txtUser").click()
    self.driver.find_element(By.ID, "txtUser").click()
    element = self.driver.find_element(By.ID, "txtUser")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, "table:nth-child(4) td").click()
    self.driver.find_element(By.CSS_SELECTOR, "td:nth-child(5)").click()
    self.driver.find_element(By.CSS_SELECTOR, "td:nth-child(5)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "td:nth-child(5)")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "txtPassword").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) > td:nth-child(2)").click()
    self.driver.find_element(By.ID, "btnLogin").click()
    self.driver.find_element(By.ID, "txtUser").click()
    self.driver.find_element(By.ID, "txtUser").click()
    element = self.driver.find_element(By.ID, "txtUser")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "txtPassword").click()
    self.driver.find_element(By.ID, "txtPassword").click()
    element = self.driver.find_element(By.ID, "txtPassword")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "btnLogin").click()
    self.driver.switch_to.frame(0)
    self.driver.find_element(By.ID, "lblUserName").click()
    self.driver.find_element(By.ID, "lblUserName").click()
    self.driver.find_element(By.ID, "lblUserName").click()
    self.driver.find_element(By.ID, "lblUserName").click()
    self.driver.find_element(By.ID, "lblUserName").click()
  
