# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLiquidacionesAltaLotePrestacion():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_liquidacionesAltaLotePrestacion(self):
    self.driver.get("https://saesdesa.ospesalud.com.ar/saes/")
    self.driver.set_window_size(1936, 1048)
    self.driver.find_element(By.ID, "btnLogin").click()
    self.driver.switch_to.frame(0)
    self.driver.find_element(By.LINK_TEXT, "Liquidaciones").click()
    self.driver.find_element(By.LINK_TEXT, "Liquidaciones").click()
    self.driver.switch_to.default_content()
    self.driver.switch_to.frame(1)
    self.driver.find_element(By.LINK_TEXT, "Liquidación de Comprobantes").click()
    self.driver.switch_to.default_content()
    self.driver.switch_to.frame(2)
    self.driver.find_element(By.ID, "ctl00_cMain_imgAdd").click()
    self.driver.find_element(By.ID, "ctl00_cMain_UCTree1_UCLote1_drpTipoLiquidacion").click()
    dropdown = self.driver.find_element(By.ID, "ctl00_cMain_UCTree1_UCLote1_drpTipoLiquidacion")
    dropdown.find_element(By.XPATH, "//option[. = 'PRESTACION']").click()
    self.driver.find_element(By.ID, "ctl00_cMain_UCTree1_UCLote1_UCPrestadorPadre1_txtDescripcion").click()
    self.driver.find_element(By.ID, "ctl00_cMain_UCTree1_UCLote1_UCPrestadorPadre1_txtDescripcion").send_keys("ACLIBA")
    self.driver.find_element(By.ID, "ctl00_cMain_UCTree1_UCLote1_UCPrestadorPadre1_btnSearch").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) input").click()
    self.driver.find_element(By.ID, "ctl00_cMain_UCTree1_UCLote1_txtFechaRecepcion").click()
    self.driver.find_element(By.ID, "ctl00_cMain_UCTree1_UCLote1_txtFechaRecepcion").send_keys("30/10/2023")
    self.driver.find_element(By.ID, "ctl00_cMain_UCTree1_UCLote1_imgOK").click()
    self.driver.find_element(By.CSS_SELECTOR, "font:nth-child(2)").click()
    self.driver.close()
  
